### PR TITLE
removed an extra dnt check that always returned a warning whether col…

### PR DESCRIPTION
**Pull request by benjamingraf**
removed an extra dnt check that always returned a warning whether collectDnt was set or not

### CODE REVIEW

**Comment by adriaanvanrossum** [comment]
Thanks for creating this PR. What is the issue it solves? Does is show the DNT warning for people without DNT?

**Comment by benjamingraf** [comment]
At the moment the attribute data-collect-dnt="true" on the script element has no effect.

Line 396-417 looks as follows:

// Don't track when Do Not Track is set to true
/** if ignorednt **/
if (!collectDnt && doNotTrack in nav && nav[doNotTrack] == "1")
  return warn(
    notSending +
      "when " +
      doNotTrack +
      " is enabled. See " +
      docsUrl +
      "/dnt"
  );
/** else **/
if (doNotTrack in nav && nav[doNotTrack] == "1")
  return warn(
    notSending +
      "when " +
      doNotTrack +
      " is enabled. See " +
      docsUrl +
      "/dnt"
  );
/** endif **/

The second if-statement will therefore always return a warning as long as nav.doNotTrack is 1, without checking if collectDnt was set.

Only the first if-statement should be needed, otherwise data-collect-dnt="true" will have no effect.

**Comment by adriaanvanrossum** [comment]
Do you have a live example of that? When I test I only get the warning when DNT is enabled. Do you see something else in your console?

This is a JSfiddle in a browser with DoNotTrack:

2022-01-01-19h35-screenshot@2x

And this one without DoNotTrack:

image

I think something you should know. When you see `/** if ignorednt /` it will only be added to scripts that we export that support de ignore do not track feature. The second `warn` is for our light script. It doesn't have that ignore feature.

If this PR is based purely on our code, I think this explains it :)

**Comment by benjamingraf** [comment]
Yeah, I was just reading the code and not thinking of script exports. Sorry, my bad. :)

**Comment by adriaanvanrossum** [comment]
No worries, thanks for taking to time to improve our script! Appreciated.

**Pull request closed without merging**
